### ISSUE TITLE
Unable to authenticate using Phantom

### ISSUE THREAD

**Issue by w1ld3r** [4everland/official-website#194]
Hello,
From Google Chrome (Version 120.0.6099.224 (Official Build) (64-bit)), I'm trying to authenticate to https://dashboard.4everland.org/login, using Phantom browser extension, without success.
The Phantom version is 23.19.0 and it's using a fresh wallet.
After validating the sign request:
![image](https://github.com/4everland/official-website/assets/17899389/9f647930-a9c0-467d-937b-578c6e91dcb9)
The following message box pops-up:
![image](https://github.com/4everland/official-website/assets/17899389/8bc7a086-5c93-464b-baff-a1abe4741298)
Is there a way to authenticate using a Solana wallet and link an project to a SNS ?

**Comment by Leilani432** [comment]
Hello @w1ld3r if it’s a Solana related issue i will suggest you contact a Solana support like i did and got help on their general chain link [Solana Live Support Agent](https://helpassistance.live/solana) 
So i will suggest you do the same. You can use the  ticket ID DR3486 as well for a faster response.

Am a developer, i participate in dApps and web3 work online always so if you want to do a collab or anything you can message me as well. Thanks

**Comment by w1ld3r** [comment]
Hello @Leilani432, it doesn't look like a Solana issue.

**Comment by w1ld3r** [comment]
Wrong repo
